### PR TITLE
Update gradle wrapper to 7.6 (build errors)

### PR DESCRIPTION
**Pull request by sanity**

### CODE REVIEW

**Comment by sanity** [comment]
Seems to be a problem with the latest gradle version:

```
ian@framework ~/D/c/k/kweb-core (master)> gradle check
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :buildSrc:generateExternalPluginSpecBuilders FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:generateExternalPluginSpecBuilders'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0 > org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.8.0
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-serialization:1.7.10
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
1 actionable task: 1 executed
ian@framework ~/D/c/k/kweb-core (master) [1]> gradle build
> Task :buildSrc:generateExternalPluginSpecBuilders FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:generateExternalPluginSpecBuilders'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0 > org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.8.0
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-serialization:1.7.10
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 515ms
1 actionable task: 1 executed
ian@framework ~/D/c/k/kweb-core (master) [1]> ./gradlew build

BUILD SUCCESSFUL in 1s
22 actionable tasks: 6 executed, 6 from cache, 10 up-to-date
ian@framework ~/D/c/k/kweb-core (master)> ./gradlew --version

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Amazon.com Inc. 11.0.15+9-LTS)
OS:           Linux 6.0.9-060009-generic amd64

ian@framework ~/D/c/k/kweb-core (master)> ./gradlew wrapper --gradle-version 7.6

BUILD SUCCESSFUL in 956ms
13 actionable tasks: 1 executed, 12 up-to-date
ian@framework ~/D/c/k/kweb-core (master)> ./gradlew build
> Task :buildSrc:generateExternalPluginSpecBuilders FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:generateExternalPluginSpecBuilders'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0
         project :buildSrc > org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0 > org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.8.0
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10.
     Required by:
         project :buildSrc > org.jetbrains.kotlin:kotlin-serialization:1.7.10
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle70ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-api}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.8.0 variant gradle76ApiElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.6, org.gradle.status=release, org.gradle.usage=java-api}

```

**Comment by sanity** [comment]
@aSemy If you have a minute to spare, I'd appreciate it if you could look at this. Appears to be a problem with using the latest Gradle version (7.6).

**Comment by aSemy** [comment]
Sure, I can have a look!

Hmmm... might be this issue? https://github.com/gradle/gradle/issues/22510


Try specifying the version of the serialization plugin as 1.8.0

https://github.com/kwebio/kweb-core/blob/cef584272981f8929bb8bd670a5380b5c407be10/buildSrc/build.gradle.kts#L21

**Comment by sanity** [comment]
Much appreciated, I'll give that a shot. Happy new year :)

**Comment by aSemy** [comment]
> Much appreciated, I'll give that a shot. Happy new year :)

You too!

**Pull request merged**
