### PR TITLE
Update fomantic 2.9.3

### PR DESCRIPTION
**Pull request by Xprofi**
https://github.com/kwebio/kweb-core/issues/610

### CODE REVIEW

**Comment by Xprofi** [comment]
@sanity hi )))

**Comment by sanity** [comment]
@Xprofi Hey, sorry about the delay - will deploy now.

**Comment by sanity** [comment]
@Xprofi This is very frustrating, but Sonatype (through which I publish Kweb to Maven Central) seems to have broken the deployment process as it now requires a token instead of providing the username/password.

And to add insult to injury it appears that to get one of these tokens I need to upgrade to Sonatype Pro, which - if true - is a really ugly cash-grab by Sonatype at the expense of open source authors.

I've been growing increasingly frustrated with the JVM ecosystem's tooling and this may be the straw that broke the camel's back and convinces me to archive this project as so much of my effort over the past 2 years with it has been fighting JVM tooling, which I simply don't have time for anymore :(

**Comment by chucky2002** [comment]
@sanity 
Please don't stop developing this great project. I love it. It works great.

**Pull request merged**
