### PR TITLE
Fix CI/CD, and additional config updates

### PR DESCRIPTION
**Pull request by aSemy**
Fixing JitPack and GHA

* set JDK distribution to Temurin
* use concurrency to cancel running jobs if a newer commit is pushed
* try to fix JitPack

I think using JDK11 might be better than JDK17... but let's see how this goes.

### CODE REVIEW

**Comment by sanity** [comment]
Interesting re: JDKs, I would have assumed more recent would be better. Why do you think 11 might be preferable?

**Comment by aSemy** [comment]
Basically because 11 is more widely supported, and because Kweb is Kotlin, it doesn't really matter what version of Java it's using - only what JDK level it's compatible with.

**Comment by sanity** [comment]
@aSemy Feel free to merge to `master` if/when you think it's ready, I think you should have permissions.

**Comment by aSemy** [comment]
Okay, it looks like JitPack is working now 

https://jitpack.io/com/github/aSemy/kweb-core/feat~gha_updates-42308896e5-1/build.log

**Comment by aSemy** [comment]
Cool, thanks! 

btw, for JitPack have you set up the webhook? https://jitpack.io/docs/BUILDING/#building-ahead-of-time

**Comment by sanity** [comment]
No, wasn't aware of that, I'll take a look. Thanks so much for all your help!

**Pull request merged**
