### PR TITLE
buildSrc convention plugins

### PR DESCRIPTION
**Pull request by aSemy**
This PR includes changes from https://github.com/kwebio/kweb-core/pull/319

Set up some [convention plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins), so Gradle build config can be modularised and applied as required. 

* `buildsrc.convenions.base` - language independent config, for all subprojects
* `buildsrc.convenions.kotlin-jvm` - defines common config for Kotlin JVM
* `buildsrc.convenions.maven-publish` - creates Maven publications, as required

I've defined a useful helper in the `maven-publish` convention, so it's easier to test and verify the whole flow. Just run 

```
./gradlew publishAllPublicationsToMavenProjectLocalRepository
```

and the whole project will be published to `$rootDir/build/maven-project-local`, so you can check to see if the publication works as expected

### CODE REVIEW

**Comment by sanity** [comment]
> ./gradlew publishAllPublicationsToMavenProjectLocalRepository

This looks useful, do you think it would be beneficial to add it to Github Actions CI as a verification step?

**Comment by aSemy** [comment]
> > ./gradlew publishAllPublicationsToMavenProjectLocalRepository
> 
> This looks useful, do you think it would be beneficial to add it to Github Actions CI as a verification step?

Hmmm possibly... But normally the publication runs okay. Running `./gradlew build` is the important one. For the publication to be useful you'd need to set up the GitHub Workflow to 'publish' the resulting directory, and then download and examine the results.

It's something to keep in mind!

**Comment by sanity** [comment]
@aSemy Ugh, not sure what the problem is but after merging these into `master` I'm getting some [build issues](https://github.com/kwebio/kweb-core/actions/runs/3221819516/jobs/5270207523). Weird because each branch seemed fine in isolation.

I have a call in a minute so it will be later today before I can investigate, but would appreciate it if you could take a look.

**Comment by sanity** [comment]
@aSemy JitPack is also [failing](https://jitpack.io/com/github/kwebio/kweb-core/-bcc0344975-1/build.log) now, likely due to the same issue.

**Comment by sanity** [comment]
@aSemy I've added you to the kweb-core repo in case this helps.

**Comment by aSemy** [comment]
no problem, I think they're minor fixes 👍

**Comment by sanity** [comment]
@aSemy Oh, if you want to chat in realtime I'm on [Matrix](https://matrix.to/#/#kweb:matrix.org).

**Pull request merged**
